[build.environment]
  GIT_LFS_ENABLED = "true"

[[headers]]
  for = "/videos/*"
  [headers.values]
    Cache-Control = "public, max-age=2592000, immutable"
    
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600, must-revalidate"
